# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                    # Set to true for using managed identity
    userAssignedIdentityID: <MANAGED_IDENTITY_CLIENT_ID>            # We will use the system identity
    keyvaultName: keyvault-fehemi                                   # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: order-queue-hostname
          objectType: secret
        - |
          objectName: order-queue-username
          objectType: secret
        - |
          objectName: order-queue-password
          objectType: secret
        - |
          objectName: order-queue-port
          objectType: secret
        - |
          objectName: order-queue-name
          objectType: secret
    tenantId: 314adf41-d121-41b5-b407-f395a91a6a75                 # The tenant ID of the key vault
  secretObjects:
    - secretName: azure-csi-sync-secret
      type: Opaque
      data:
        - objectName: order-queue-hostname
          key: order-queue-hostname
        - objectName: order-queue-username
          key: order-queue-username
        - objectName: order-queue-password
          key: order-queue-password
        - objectName: order-queue-port
          key: order-queue-port
        - objectName: order-queue-name
          key: order-queue-name

      